'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ogrenci
    Public Property ogrId As Integer
    Public Property ogrNo As String
    Public Property ogrAdsoyad As String
    Public Property ogrMail As String
    Public Property ogrYas As Integer

End Class
